title: Matthias Moulin's Blog
baseurl: /blog

highlighter: rouge
markdown: kramdown

sass:
 style: compressed

exclude:
- README.md

plugins: 
 - jekyll-paginate

kramdown:
    coderay:
       coderay_tab_width: 4
