title: Matthias Moulin's Blog
baseurl: /blog
main_site: https://matt77hias.github.io

markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge

compress_html:
  clippings: [html, div, p, ul, td, h1, h2, h3, h4, link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

exclude:
- README.md
- _sass/

