title: Matthias Moulin's Blog
baseurl: /blog

highlighter: rouge
markdown: kramdown

sass:
 style: compressed

exclude:
- README.md

plugins: 
 - jekyll-paginate

kramdown:
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
